version: '3'

services:
  sync:
    hostname: sync
    image: ${CRWI_IMAGENAME_ARMHF}
    restart: ${CRWI_RESTART_POLICY}
    environment:
      - EXCHANGE_API_KEY
      - EXCHANGE_API_SECRET
      - CRWI_ARGS=sync --period=$CRWI_SYNC_PERIOD --db-url=mongodb://mongo:27017/cryptoexchange-wallet
    links:
      - mongo
  
  mongo:
    image: sumglobal/rpi-mongodb
    ports:
      - 28017:27017
    volumes: 
      - ${CRWI_MONGO_VOLUME_DB}:/data/db
      - ${CRWI_MONGO_VOLUME_CONFIG}:/data/configdb