version: '3'

services:
  sync:
    hostname: sync
    image: ${CREXD_IMAGENAME_X86}
    restart: ${CREXD_RESTART_POLICY}
    environment:
      - EXCHANGE_API_KEY
      - EXCHANGE_API_SECRET
      - CREXD_ARGS=sync --period=$CREXD_SYNC_PERIOD --db-url=mongodb://mongo:27017/$CREXD_MONGO_DBNAME
    links:
      - mongo
  
  mongo:
    image: mongo:3.4
    ports:
      - 28017:27017
    volumes: 
      - ${CREXD_MONGO_VOLUME_DB}:/data/db
      - ${CREXD_MONGO_VOLUME_CONFIG}:/data/configdb